# Generated by Django 5.2.5 on 2025-08-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown Phone', max_length=100)),
                ('price', models.FloatField(null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('release_date', models.DateField(null=True)),
                ('lte_exists', models.BooleanField(null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
